#region License agreement statement

/*
 *
 * (c) Copyright Ascensio System Limited 2010-2018
 *
 * This program is freeware. You can redistribute it and/or modify it under the terms of the GNU 
 * General Public License (GPL) version 3 as published by the Free Software Foundation (https://www.gnu.org/copyleft/gpl.html). 
 * In accordance with Section 7(a) of the GNU GPL its Section 15 shall be amended to the effect that 
 * Ascensio System SIA expressly excludes the warranty of non-infringement of any third-party rights.
 *
 * THIS PROGRAM IS DISTRIBUTED WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF MERCHANTABILITY OR
 * FITNESS FOR A PARTICULAR PURPOSE. For more details, see GNU GPL at https://www.gnu.org/copyleft/gpl.html
 *
 * You can contact Ascensio System SIA by email at sales@onlyoffice.com
 *
 * The interactive user interfaces in modified source and object code versions of ONLYOFFICE must display 
 * Appropriate Legal Notices, as required under Section 5 of the GNU GPL version 3.
 *
 * Pursuant to Section 7 § 3(b) of the GNU GPL you must retain the original ONLYOFFICE logo which contains 
 * relevant author attributions when distributing the software. If the display of the logo in its graphic 
 * form is not reasonably feasible for technical reasons, you must include the words "Powered by ONLYOFFICE" 
 * in every copy of the program you distribute. 
 * Pursuant to Section 7 § 3(e) we decline to grant you any rights under trademark law for use of our trademarks.
 *
*/

#endregion License agreement statement

using System;
using ASC.Projects.Core.DataAccess.Domain.Entities.Interfaces;
using ASC.Projects.Core.DataAccess.Domain.Enums;
using ASC.Projects.Core.DataAccess.EF.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ASC.Projects.Core.DataAccess.Domain.Entities
{
    /// <summary>
    /// Represents a report template.
    /// </summary>
    public class DbReportTemplate : BaseDbEntity<int>, ITenantEntity<int>
    {
        /// <summary>
        /// Name of report template.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Type of report.
        /// </summary>
        public ReportType Type { get; set; }

        /// <summary>
        /// Filter.
        /// </summary>
        public string Filter { get; set; }

        /// <summary>
        /// Cron.
        /// </summary>
        public string Cron { get; set; }

        /// <summary>
        /// Date when this report template was created.
        /// </summary>
        public DateTime CreationDate { get; set; }

        /// <summary>
        /// Id of user who was created this report template.
        /// </summary>
        public Guid? CreatorId { get; set; }

        /// <summary>
        /// Id of tenant.
        /// </summary>
        public int TenantId { get; set; }

        /// <summary>
        /// Determines, was this report template generated automatically.
        /// </summary>
        public bool IsAutoGenerated { get; set; }

        /// <summary>
        /// Describes a set of entity-to-table mapping rules.
        /// </summary>
        public class MySqlMappingConfig : IEntityTypeConfiguration<DbReportTemplate>
        {
            public void Configure(EntityTypeBuilder<DbReportTemplate> builder)
            {
                builder.ToTable("report_template");

                builder.HasKey(rt => rt.Id);

                builder.Property(rt => rt.Name)
                    .HasColumnType("varchar(1024)")
                    .HasMaxLength(1024);

                builder.Property(rt => rt.Type)
                    .HasColumnType("int");

                builder.Property(rt => rt.Filter)
                    .HasColumnType("text");

                builder.Property(rt => rt.Cron)
                    .HasColumnType("varchar(255)")
                    .HasMaxLength(255);

                builder.Property(rt => rt.CreationDate)
                    .HasColumnName("create_on")
                    .HasColumnType("timestamp")
                    .HasDefaultValue();

                builder.Property(rt => rt.CreatorId)
                    .HasColumnName("create_by")
                    .HasColumnType(MySqlMappingConfigurationConstants.GuidDbType);

                builder.Property(rt => rt.IsAutoGenerated)
                    .HasColumnName("auto")
                    .HasColumnType("int")
                    .HasDefaultValue();
            }
        }
    }
}
